### ISSUE TITLE
Milestone 4 parandused

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#102]
- [x] Materialboxi pildi kuvasuhe 1.50 mitte 1.38:1 (lahendatatkse #101 raames)
- [x] Materialboxi pealkirja tähemärke peab juurde tekkima mitte vähenema versus 1.2.0, näide Paperis
- [ ] punase päise puhul aktiivne vasakmenüü punkdi värv sinise asemel punane (refereeritud Issue 21 lahendamata punane number)
- [x] vasakmenüüpunktil klikkides ei vii lehe sisuosa õigesse kogumiku peatükki, nt #chapter-1
- [x] kui olla kogumiku muutmise režiimis ja lisan koolikoti välise URLi uue materjalina, siis materjali lisamise dialoog vilgub eest ära mingil sagedusel
- [x] Ava täpne otsing- Haridus- vali üks haridus- Sulge täpne otsing-Ava täpne otsing- VIGA! Haridus ei ole kustunud

**Comment by atatter** [comment]
@aivo0 ootame speci

**Comment by atatter** [comment]
@erkkijakobson @aivo0  Tekkisid mõned küsimused: 
1. - 2. Joondused, parandused xl murdepunktil: võiks täpsemalt paika panna kuidas layout käitub erinevate laiustega ekraanidel. Google inboxi ei saa täielikult aluseks võtta, kuna sellel puudub mobiilne vaade. 
- Milline on joondumine laial ekraanil kus sidenavi avamine/sulgemine ei mõjuta sisu paigutust?
- Milline on joondumine veidi kitsamal ekraanil kus sidenavi avamine/sulgemine mõjutab sisu paigutust, ehk lükkab sisu eest ära? 
- Milline on sisu joondumine mobiilses vaates, kus sidenav asub sisu peal? 
- Milline on päise sisu paigutus kõigis eelnevates punktides?
- Mis on väikeste kaartide suurused erinevatel ekraanide laiustel?

Ettepanek: Kuna Google Keep'i kujundus on uuem ja sellel on ka mobiilne vaade, siis võiks  äkki selle aluseks võtta.

3. Materialboxi pildi kuvasuhe 1.50 - Kas see tähendab seda, et pilt on pool materialboxi kõrgusest?
4. Materialboxi tähemärkide arv - See punkt on milestone 7 taskis kus toimub väikse kaardi muutmine #22 #90 Mõistlik oleks seda siis teha
5. Punase päise puhul vasakmenüü punkti värv punane - mis siis juhtub, kui päise värv on lilla?

**Comment by aivo0** [comment]
Koosolekult 05.12.16: esimese punktiga ei vaja selle taski all parandamist (vasakmenüü, sisuosa kui ka materialboxid ja nende suuruse parandus xl murdepunktil).

**Comment by KailiAll** [comment]
@erkkijakobson 
Palun täpsusta kommentaaridesse viga:
punase päise puhul aktiivne vasakmenüü punkdi värv sinise asemel punane (refereeritud Issue 21 lahendamata punane number)

Kus ja mis on hetkel valesti?
Mis rolliga/rollidega ja kus vaates/vaadetes peab kasutaja olema?

**Comment by erkkijakobson** [comment]
admin menüü ja selle allolevad punktid ja peavad nii hover kui valitud olekus olema punased nagu päis, et number neis oleks sinise asemel punane

**Comment by KailiAll** [comment]
@erkkijakobson 
parandused tehtud ja testitavad oxygenis
