### ISSUE TITLE
Milestone 8 & 9 parandused

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#172]
- [x] kogumikku lisatud piltide (süsteemne materjal) asemele ilmuvad tillukesed ruudud https://e-koolikott.ee/portfolio?id=7377 (viimased peatükid)
- [x] kogumik salvestab baasi lubamatut vormindust, mille vältimiseks oli varasemalt nõue markdowniks convertida (ei pidanud aga vaja olema?) https://e-koolikott.ee/portfolio?id=7377
- [x] litsentsi tõlge (nt CC BY SA) ei ilmu kasutajaliidesesse (ei materjali lisamise vaatesse ega detailvaatesse) peale selle määramist Translations tabelis
- [x] üldpädevus ei mahu detailvaates üksinda ära: kuvab ainult "Matemaatika-, loodusteaduste- ja ..." https://e-koolikott.ee/material?id=7381
- [x] enne Issuet 57 lisatud õppekirjandus ei tule enam välja otsingust vastavalt määrusele Issue lingis, nt https://e-koolikott.ee/material?id=2
- [x] touri parandus

**Comment by KailiAll** [comment]
@erkkijakobson 

Palun täpsusta neid vigu järgmiselt:
1. Näide veast
2. Kuidas viga täpselt korrata
3. Täpne oodatud tulemus

**Comment by erkkijakobson** [comment]
täpsustasin

**Comment by martlausNG** [comment]
"litsentsi tõlge (nt CC BY SA) ei ilmu kasutajaliidesesse (ei materjali lisamise vaatesse ega detailvaatesse) peale selle määramist Translations tabelis" - dop.hm keskkonnas on olemas tõlge, äkki on cachet vaja puhastada? 
![ccbysa](https://cloud.githubusercontent.com/assets/12746653/23579511/bad47b78-00f7-11e7-9fca-99b6446e1e3d.png)

**Comment by erkkijakobson** [comment]
Tõlge toodangu baasis:
![image](https://cloud.githubusercontent.com/assets/16906555/23705355/1a111052-0412-11e7-90a7-44e2a6c4ab12.png)

Tõlge puudu inkognito aknas meta muutmisel:
![image](https://cloud.githubusercontent.com/assets/16906555/23705385/48f5d204-0412-11e7-9dde-631d7fdad770.png)

Tõlge puudu detailvaates:
![image](https://cloud.githubusercontent.com/assets/16906555/23705413/6479ef9c-0412-11e7-84f2-5b068d2e318b.png)
https://e-koolikott.ee/material?id=7344

**Comment by martlausNG** [comment]
Ei paista, et tõlget oleks toodangus muudetud nagu on ta dop.hm.ee keskkonnas muudetud. Lives on: https://ekoolikott.ee/rest/translation?lang=est (vana tõlge) ja dop.hm.ee-s on: https://dop.hm.ee/rest/translation?lang=est (uus tõlge). Äkki on Lives jäänud vana tõlge kustutamata? 
Seega viga pole programmaatiline ja ilma ligipääsuta baasile ei saa rohkem midagi teha.

**Comment by erkkijakobson** [comment]
Safari cache puhastatud (_manage website data > remove all_) - vasakul tavaaken, paremal privaataken
![image](https://cloud.githubusercontent.com/assets/16906555/23854608/bf7cfe52-07fa-11e7-8683-52be57012f2f.png)

**Comment by gglukmann** [comment]
Safari privaataken ei võimalda localStorage't kasutada, sellepärast ka error ning pilti ei ole.

**Comment by erkkijakobson** [comment]
mis lahendus Safari kasutajale siis tuleb?

**Comment by erkkijakobson** [comment]
ülaltoodud kogumiku paranduste testimisel arvestada ka muutmisrežiimiga, kus esineb tekstikadu:
![image](https://cloud.githubusercontent.com/assets/16906555/23902333/719616e0-08c9-11e7-8c72-dcd18b971f91.png)

**Comment by Pirgit** [comment]
![image](https://cloud.githubusercontent.com/assets/17288515/23998004/56d52bf4-0a5c-11e7-91bd-16b3c7baacd6.png)

**Comment by Pirgit** [comment]
Logisin esimest korda ID-kaardiga sisse. Vajutasin Näita tuuri, kuvas järgneva akna aga selle juures ei saa enam midagi vajutada.

**Comment by KailiAll** [comment]
Mis Chrome versiooniga tuuri ei ole võimalik klikkida?
Lisasin pildi, kust saada Chrome versiooni nr.
![image](https://cloud.githubusercontent.com/assets/19947450/24138727/04e48668-0e22-11e7-8e1c-2a8da84f7391.png)

**Comment by Pirgit** [comment]
Chrome version 56.0.2924.87

**Comment by KailiAll** [comment]
Tour on nüüd parandatud ja tuleb järgmise versiooniga.
