### ISSUE TITLE
Milestone 8 & 9 parandused v2

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#173]
- [x] materjali lisamisel:autori lisamisel eesnimi, tab, perenimi, tab, enter = uus autor: ei teki enam võimalust kohe tippida (ligipääsetavus)
- [x] Safari ei kuva lehte privaataknas (inkognito) peale esimest preloaderit jääb paljas taust (sama ka oxygeniga)

- [x] ülaltoodud kogumiku paranduste testimisel arvestada ka muutmisrežiimiga, kus esineb tekstikadu:
![image](https://cloud.githubusercontent.com/assets/16906555/23902333/719616e0-08c9-11e7-8c72-dcd18b971f91.png)

Lisainfo: tarne versioon peaks tulema semveri põhiselt 1.9.x

**Comment by gglukmann** [comment]
Tabid hakkavad siis tööle safaris, kui need sisse lülitada. "Preferences > Advanced > Press tab to highlight each item on a page". Sellele workaroundi pole.
